version: '3'
services:
  mysql:
    image:  mysql:8.0.3
    ports:
      -  3306:3306
    environment:
      -  MYSQL_ROOT_PASSWORD=dbpass
      -  MYSQL_DATABASE=demo
  mongo:
    image:  mongo:3.0
    ports:
      -  27017:27017
  redis:
    image:  redis:4-alpine
    ports:
      -  6379:6379
