version: '3'

services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

  selenium-runner:
    build: ./selenium-runner
    image: demo-selenium-runner
    volumes:
      - ./webtests:/webtests
      - ./maven-home:/root/.m2
    depends_on:
      - selenium-chrome
